import { Trash2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

import type {
  CustomToolInput,
  CustomToolInputType,
} from "../model/customToolTypes";
import { inputTypeOptions } from "./inputTypeOptions";
import { renameAutoGeneratedInputIdForType } from "./inputIdUtils";

type CustomToolInputRowProps = {
  input: CustomToolInput;
  onChange: (input: CustomToolInput) => void;
  onRemove: () => void;
};

export function CustomToolInputRow({
  input,
  onChange,
  onRemove,
}: CustomToolInputRowProps) {
  const updateInput = (
    field: keyof CustomToolInput,
    value: CustomToolInput[keyof CustomToolInput],
  ) => {
    onChange({
      ...input,
      [field]: value,
    });
  };

  const updateType = (nextType: CustomToolInputType) => {
    onChange({
      ...input,
      id: renameAutoGeneratedInputIdForType(input.id, input.type, nextType),
      type: nextType,
    });
  };

  return (
    <div className="grid gap-4 rounded-xl border p-4">
      <div className="flex items-start justify-between gap-3">
        <div className="grid flex-1 gap-2">
          <Label htmlFor={`${input.id}-label`}>Label</Label>
          <Input
            id={`${input.id}-label`}
            value={input.label}
            onChange={(event) => updateInput("label", event.target.value)}
          />
        </div>

        <Button variant="outline" size="icon" onClick={onRemove}>
          <Trash2 className="size-4" />
        </Button>
      </div>

      <div className="grid gap-2">
        <Label htmlFor={`${input.id}-internal-id`}>Input ID</Label>
        <Input
          id={`${input.id}-internal-id`}
          value={input.id}
          placeholder="example: testFilesFolder"
          onChange={(event) => updateInput("id", event.target.value)}
        />
        <p className="text-xs text-muted-foreground">
          Blocks must reference this ID in their JSON config. Use no spaces.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="grid gap-2">
          <Label htmlFor={`${input.id}-type`}>Type</Label>
          <select
            id={`${input.id}-type`}
            className="h-9 rounded-md border bg-background px-3 text-sm"
            value={input.type}
            onChange={(event) =>
              updateType(event.target.value as CustomToolInputType)
            }
          >
            {inputTypeOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </div>

        <label className="flex items-end gap-2 text-sm">
          <input
            type="checkbox"
            checked={input.required}
            onChange={(event) => updateInput("required", event.target.checked)}
          />
          Required input
        </label>
      </div>

      <div className="grid gap-2">
        <Label htmlFor={`${input.id}-description`}>Help text</Label>
        <Input
          id={`${input.id}-description`}
          value={input.description ?? ""}
          placeholder="Explain what the user should provide."
          onChange={(event) => updateInput("description", event.target.value)}
        />
      </div>
    </div>
  );
}