import { Button } from "@/components/ui/button";
import type { CustomToolFoundationBlockType } from "../../../../domain/customToolTypes";
import {
  ExpressionConfigField,
  SelectConfigField,
  type FoundationConfigEditorProps,
  updateFoundationConfig,
} from "./FoundationConfigFields";

type FoundationOperatorBlockEditorProps = FoundationConfigEditorProps & {
  blockType: CustomToolFoundationBlockType;
};

const mathOperators = [
  "add",
  "subtract",
  "multiply",
  "divide",
  "modulo",
  "power",
] as const;

const compareOperators = [
  "equals",
  "not_equals",
  "greater_than",
  "greater_or_equal",
  "less_than",
  "less_or_equal",
] as const;

function configString(value: unknown, fallback = "") {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function CopyableResultId({ value }: { value: unknown }) {
  const id = configString(value, "not-generated-yet");

  const copyId = () => {
    if (!navigator.clipboard || id === "not-generated-yet") return;
    void navigator.clipboard.writeText(id);
  };

  return (
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-background/60 p-3">
      <div>
        <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          Automatic result id
        </p>
        <code className="mt-1 block rounded-md bg-muted px-2 py-1 text-sm">
          {id}
        </code>
        <p className="mt-1 text-xs text-muted-foreground">
          This id is generated by the block. Connect the Result port instead of typing it.
        </p>
      </div>
      <Button type="button" variant="outline" size="sm" onClick={copyId}>
        Copy id
      </Button>
    </div>
  );
}

export function FoundationOperatorBlockEditor({
  blockType,
  config,
  onConfigChange,
  referenceOptions,
  linkedInputSuggestions,
}: FoundationOperatorBlockEditorProps) {
  const update = (patch: Record<string, unknown>) => {
    updateFoundationConfig(config, onConfigChange, patch);
  };

  if (blockType === "math.operation") {
    return (
      <div className="space-y-4 rounded-2xl border border-amber-500/30 bg-amber-500/5 p-4">
        <CopyableResultId value={config.resultName} />
        <SelectConfigField
          label="Math operator"
          value={config.operator}
          options={mathOperators}
          onChange={(operator) => update({ operator })}
          description="For factorial choose multiply."
        />
        <ExpressionConfigField
          label="Left number"
          value={config.left}
          onChange={(left) => update({ left })}
          acceptedTypes={["number"]}
          referenceOptions={referenceOptions}
          linkedInputSuggestions={linkedInputSuggestions}
          placeholder="Connect result/current value here"
          description="Connect a number output into the Left port, or choose a canvas value."
        />
        <ExpressionConfigField
          label="Right number"
          value={config.right}
          onChange={(right) => update({ right })}
          acceptedTypes={["number"]}
          referenceOptions={referenceOptions}
          linkedInputSuggestions={linkedInputSuggestions}
          placeholder="Connect i here"
          description="Connect another number output into the Right port."
        />
      </div>
    );
  }

  if (blockType === "logic.compare") {
    return (
      <div className="space-y-4 rounded-2xl border border-violet-500/30 bg-violet-500/5 p-4">
        <CopyableResultId value={config.resultName} />
        <SelectConfigField
          label="Comparison"
          value={config.operator}
          options={compareOperators}
          onChange={(operator) => update({ operator })}
        />
        <ExpressionConfigField
          label="Left value"
          value={config.left}
          onChange={(left) => update({ left })}
          referenceOptions={referenceOptions}
          linkedInputSuggestions={linkedInputSuggestions}
          placeholder="Connect the left value here"
        />
        <ExpressionConfigField
          label="Right value"
          value={config.right}
          onChange={(right) => update({ right })}
          referenceOptions={referenceOptions}
          linkedInputSuggestions={linkedInputSuggestions}
          placeholder="Connect the right value here"
        />
      </div>
    );
  }

  return null;
}
