import type { CustomToolInputType } from "../../model/customToolTypes";

function createRandomIdPart() {
  if (globalThis.crypto?.randomUUID) {
    return globalThis.crypto.randomUUID().slice(0, 8);
  }

  return Math.random().toString(36).slice(2, 10);
}

function safeInputType(type: CustomToolInputType) {
  return type.replace(/[^a-zA-Z0-9]/g, "-");
}

export function createInputId(type: CustomToolInputType) {
  return `${safeInputType(type)}-input-${createRandomIdPart()}`;
}

export function renameAutoGeneratedInputIdForType(
  inputId: string,
  oldType: CustomToolInputType,
  nextType: CustomToolInputType,
) {
  const oldPrefix = `${safeInputType(oldType)}-input-`;

  if (!inputId.startsWith(oldPrefix)) {
    return inputId;
  }

  return `${safeInputType(nextType)}-input-${inputId.slice(oldPrefix.length)}`;
}